### ISSUE TITLE
Lusas_Toolkit: Reading SectionProperty applied with two different materials

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Lusas_Toolkit#166]
When pulling a `SectionProperty `that has been applied with two distinct `Material `objects, only the latest `Material `object will be assigned to the `SectionProperty `when read in to a Dictionary, e.g. when `ReadSectionProperties `is called in the `ReadBars `method.

This arises because `Material `objects are not assigned to `SectionProperty` objects in Lusas, instead they are both assigned to `Bar` objects. This results in only,a single `SectionProperty `being returned when two `SectionProperty `objects with the same `SectionProfile `and attributes, but different `Material `properties.

**Comment by KalleEdstroem** [comment]
When pulling a bar (with a `SectionProperty`) I can only see this being a problem when naming the 2 `SectionProperty` identically which in itself is an error. Otherwise I do not find this bug when it goes through the `ReadBars` method. Since with unique names Lusas handles the 2 section properties as 2 unique things and gets there material correct.

On another note when you try to pull a `SectionProperty` as itself with the `ISectionProperty` type request you will not get any information regarding the material. The material is handled in the `ToBar` method using information about the `lusasline` and what section and material it has assigned to it. 

It would have to be some restructure of the code to get the information about the material assigned to the `SectionProperty` straight away.

A script showing everything I have mentioned:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23166-Reading%20SectionProperty%20applied%20with%20two%20different%20materials.gh?csf=1&web=1&e=qWxIhU

**Comment by peterjamesnugent** [comment]
Agree with @KalleEdstroem's assessment and we can close this issue as the `ISectionProperty` require unique names.
