### ISSUE TITLE
Lusas_Toolkit: Resolve warnings

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Lusas_Toolkit#202]
**By 30th November please**

#### Broken rules:
Compiler warnings occur when compiling the toolkit.

#### Suggestions to restore compliance:
Ensure code compiles without any warnings.

**Comment by peterjamesnugent** [comment]
This is the warning that is occurring, and is also present on other toolkits:
> Severity	Code	Description	Project	File	Line	Suppression State
> Warning		There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "Lusas.Interop, Version=17.0.1633.29698, Culture=neutral, PublicKeyToken=ee620220e102840a, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	Lusas_Engine			

I have made the various projects (Lusas_oM, Lusas_Adapter, Lusas_Engine) 32-bit (x86) to match the `Lusas.Interop.dll` and it gets rid of the warning. 

However, [Rhino is a  64-bit application](https://discourse.mcneel.com/t/referencing-32bit-dll-for-a-grasshopper-component-on-x64-win-system/47356) and therefore cannot load the Lusas_Toolkit as a 32-bit process. I have not checked this on the other UIs.

So I think this leaves us stuck in the middle. Where the referenced .dll is 32-bit, but Rhino wants 64-bit 64-bit references.

I have found this, but not sure if it is applcable to our case because the dll uses COM calls: https://docs.microsoft.com/en-us/windows/win32/winprog64/process-interoperability

**Comment by FraserGreenroyd** [comment]
@adecler tagging you in to see the above from @peterjamesnugent and get any thoughts you have on this before we move forward? :smile:

**Comment by FraserGreenroyd** [comment]
Following discussion with @al-fisher today, we are happy to let this issue go for the time being, though we may continue investigating it but am not going to hold up any ongoing updates for the time being. Thanks for the thorough review @peterjamesnugent !
